### ISSUE TITLE
Recommended list doesn't download

### ISSUE THREAD

**Issue by xenithorb** [Suyash458/soundcloud-dl#13]
```
soundcloud-dl --limit 99 https://soundcloud.com/twofeetmusic/love-is-a-bitch/recommendedConnecting ...
Downloading 99 related tracks
Traceback (most recent call last):
  File "/home/xenith/virtualenvs/soundcloud-dl3/lib64/python3.5/site-packages/soundcloud_dl/downloader/downloader.py", line 90, in getSingleTrack
    url = track['stream_url'].split('?')[0] + '?client_id='+secret
KeyError: 'stream_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xenith/virtualenvs/soundcloud-dl3/bin/soundcloud-dl", line 11, in <module>
    sys.exit(main())
  File "/home/xenith/virtualenvs/soundcloud-dl3/lib64/python3.5/site-packages/soundcloud_dl/soundcloud_dl.py", line 36, in main
    downloaderObject.Download()
  File "/home/xenith/virtualenvs/soundcloud-dl3/lib64/python3.5/site-packages/soundcloud_dl/downloader/downloader.py", line 385, in Download
    self.getRecommendedTracks(data, no_tracks)
  File "/home/xenith/virtualenvs/soundcloud-dl3/lib64/python3.5/site-packages/soundcloud_dl/downloader/downloader.py", line 150, in getRecommendedTracks
    self.getSingleTrack(track)
  File "/home/xenith/virtualenvs/soundcloud-dl3/lib64/python3.5/site-packages/soundcloud_dl/downloader/downloader.py", line 93, in getSingleTrack
    str(track['id']) + '/stream?client_id=' + browser_id
NameError: name 'browser_id' is not defined

```

**Comment by suyashb95** [comment]
@xenithorb I know this is 2 years late but is this still an issue?
