### ISSUE TITLE
Playlist download not finishing sc-dl 0.1.26

### ISSUE THREAD

**Issue by oorxx** [Suyash458/soundcloud-dl#26]
When i try to download any playlist it downloads some tracks then stops and gives this error : 

```python
Traceback (most recent call last):
  File "c:\users\orx\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\orx\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\orx\AppData\Local\Programs\Python\Python39\Scripts\sc-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\soundcloud_dl.py", line 64, in main
    d.main()
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\downloader\downloader.py", line 218, in main
    self.get_playlist(data)
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\downloader\downloader.py", line 81, in get_playlist
    self.get_multiple_tracks(playlist.tracks)
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\downloader\downloader.py", line 77, in get_multiple_tracks
    self.get_single_track(track)
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\downloader\downloader.py", line 63, in get_single_track
    metadata = self.get_track_metadata(track)
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\downloader\downloader.py", line 50, in get_track_metadata
    url, fileFormat = self.get_track_url(track)
  File "c:\users\orx\appdata\local\programs\python\python39\lib\site-packages\downloader\downloader.py", line 33, in get_track_url
    if track["downloadable"] and "download_url" in track:

KeyError: 'downloadable'
```

**Comment by suyashb95** [comment]
@oorxx Thanks for reporting!

**Comment by oorxx** [comment]
Does that bug affect you too ?

**Comment by suyashb95** [comment]
@oorxx I haven't come across this one so far but it looks like a particular track in the playlist has no metadata. Which playlist are you trying to fetch?

**Comment by oorxx** [comment]
I tried with any playlist it always does it

**Comment by Zura-01** [comment]
Track 6 on this playlist fails with same error: `https://soundcloud.com/lemmymii/sets/heavens-feel-ii-lost-butterfly-ost`

EDIT: actually every track after No.5. fails, but only when downloading the playlist. Downloading individual mp3s works fine

**Comment by leoflowers** [comment]
Ran into this problem today. Same scenario, track metadata does not seem to show up after the fourth or fifth song in playlist. I'll be looking into it some more in the coming days

**Comment by suyashb95** [comment]
@Larvitar, @leoflowers thanks for looking into this! I'll try to debug this but might not have the time to fix this. I'd really appreciate a PR if either of you have the time though :)

**Comment by Fahrenheit** [comment]
Same bug on 2 playlists I've tried. 

```Cannot download Gorillaz - Dare (Noize Generation Remix)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/soundcloud-dl", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/soundcloud_dl.py", line 64, in main
    d.main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/downloader/downloader.py", line 218, in main
    self.get_playlist(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/downloader/downloader.py", line 81, in get_playlist
    self.get_multiple_tracks(playlist.tracks)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/downloader/downloader.py", line 77, in get_multiple_tracks
    self.get_single_track(track)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/downloader/downloader.py", line 63, in get_single_track
    metadata = self.get_track_metadata(track)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/downloader/downloader.py", line 50, in get_track_metadata
    url, fileFormat = self.get_track_url(track)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/downloader/downloader.py", line 33, in get_track_url
    if track["downloadable"] and "download_url" in track:
KeyError: 'downloadable'```
