### ISSUE TITLE
Error when genre is not set for track

### ISSUE THREAD

**Issue by erwinelling** [Suyash458/soundcloud-dl#9]
Ran into this error:

```
Connecting ... 
Single playlist found.
2 tracks found in this playlist
Traceback (most recent call last):
  File "download.py", line 8, in <module>
    downloaderObject.Download()
  File "/Users/erwinelling/.virtualenvs/verhalen/lib/python2.7/site-packages/soundcloud_dl/downloader/downloader.py", line 355, in Download
    self.getPlaylists(data)
  File "/Users/erwinelling/.virtualenvs/verhalen/lib/python2.7/site-packages/soundcloud_dl/downloader/downloader.py", line 109, in getPlaylists
    self.getSingleTrack(track)
  File "/Users/erwinelling/.virtualenvs/verhalen/lib/python2.7/site-packages/soundcloud_dl/downloader/downloader.py", line 71, in getSingleTrack
    'genre':track['genre'].encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

Think it might be that there is not genre set for this track. It might be fixed by changing line 71 in downloader/downloader.py from:

```
            'genre':track['genre'].encode('utf-8')
```

to:

```
            'genre':track.get('genre','').encode('utf-8')
```

But I don't know for sure and am note sure of how to change it and do a pull request.

**Comment by suyashb95** [comment]
Thanks for pointing that out, I think the change you've suggested is the way to go. Could you send me the URL of that particular playlist so I can test it?

**Comment by erwinelling** [comment]
Yes, this is my test playlist:
https://soundcloud.com/user-787148065/sets/misc

**Comment by suyashb95** [comment]
Thank you, fixed [here](https://github.com/Suyash458/soundcloud-dl/commit/1aecf047cfdfa17c8d55c89ac641e1283a952d52). Turns out dict.get() didn't work since the track's dictionary has genre as None when it's unknown.
